config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :recipes, only: [:show, :new, :create, :edit, :update, :destroy] do

    member do
      post 'favorite'
      delete 'unfavorite'
    end

    collection do
      get 'search'
    end
  end
  resources :cuisines, only: [:show, :new, :create, :edit, :update]
  resources :recipe_types, only: [:show, :new, :create, :edit, :update]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :recipes, dependent: :destroy
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :user
  belongs_to :recipe_type
  has_many :favorites, dependent: :destroy
  validates :title, :recipe_type, :difficulty, :cook_time, presence: true
  has_attached_file :image, styles: { medium: '300x300>', thumb: '120x90#' }
  validates_attachment :image, content_type: { content_type: ['image/jpeg',
                                                              'image/gif',
                                                              'image/png'] }
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :recipes, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :city, presence: true
  has_many :favorites, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def favorite?(recipe)
    favorite_recipes.include?(recipe)
  end

  def owner_recipe?(recipe)
    recipe.user == self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :city,
                                                       :facebook, :twitter])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :city,
                                                              :facebook,
                                                              :twitter])
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :admin_only, except: :show
  before_action :set_cuisine, only: [:show, :edit, :update]

  def show
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new(cuisine_params)
    if @cuisine.save
      redirect_to @cuisine
    else
      flash.now[:error] = 'Você deve informar o nome da cozinha'
      render :new
    end
  end

  def edit
    @cuisines = Cuisine.all if current_user.admin?
  end

  def update
    if @cuisine.update(cuisine_params)
      redirect_to @cuisine
    else
      @cuisines = Cuisine.all
      flash.now[:error] = 'Você deve informar todos os dados da receita'
      render :edit
    end
  end

  private

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end

  def admin_only
    redirect_to root_path, alert: 'Sem permissão' unless current_user.admin?
  end

  def set_cuisine
    @cuisine = Cuisine.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.last(6)
    @cuisines = Cuisine.all
    @recipe_types = RecipeType.all

    aux_favorite = Favorite.group(:recipe_id).count.sort_by { |_a, b| b }
    @favorite_recipe = aux_favorite.reverse.first(3).to_h
    @favorite = []
    @favorite_recipe.each_entry do |a, _b|
      @favorite << Recipe.find(a)
    end
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :admin_only, except: :show
  before_action :set_recipe_type, only: [:show, :edit, :update]

  def show
  end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(recipe_type_params)
    if @recipe_type.save
      redirect_to @recipe_type
    else
      flash.now[:error] = 'Você deve informar todos os dados da receita'
      render :new
    end
  end

  def edit
    @recipe_types = RecipeType.all if current_user.admin?
  end

  def update
    if @recipe_type.update(recipe_type_params)
      redirect_to @recipe_type
    else
      @recipe_types = RecipeType.all
      flash.now[:error] = 'Você deve informar todos os dados da receita'
      render :edit
    end
  end

  private

  def recipe_type_params
    params.require(:recipe_type).permit(:name)
  end

  def admin_only
    redirect_to root_path, alert: 'Sem permissão' unless current_user.admin?
  end

  def set_recipe_type
    @recipe_type = RecipeType.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :favorite,
                                    :unfavorite, :destroy]
  before_action :set_cuisines, only: [:new]

  def show
  end

  def new
    @recipe = Recipe.new
    @recipe_types = RecipeType.all
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to @recipe
    else
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      flash.now[:error] = 'Você deve informar todos os dados da receita'
      render :new
    end
  end

  def edit
    if current_user == @recipe.user
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
    else
      flash[:notice] = 'Sem permissão para editar esta receita'
      redirect_to root_path
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      @cuisines = Cuisine.all
      @recipe_types = RecipeType.all
      flash.now[:error] = 'Você deve informar todos os dados da receita'
      render :edit
    end
  end

  def search
    @search = params[:search]
    @results = Recipe.where(
      'title LIKE ? OR ingredients LIKE ?', "%#{@search}%", "%#{@search}%"
    )
    flash.now[:error] = 'Nenhuma receita encontrada' if @results.empty?
  end

  def favorite
    Favorite.create(user: current_user, recipe: @recipe)
    flash[:success] = 'Receita favoritada com sucesso'
    redirect_to @recipe
  end

  def unfavorite
    fav = Favorite.find_by(user: current_user, recipe: @recipe)
    fav.destroy
    flash[:success] = 'Receita desfavoritada com sucesso'
    redirect_to @recipe
  end

  def destroy
    @recipe.destroy
    flash[:success] = 'Receita removida com sucesso'
    redirect_to root_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id,
                                   :difficulty, :cook_time, :ingredients,
                                   :method, :image, :highlight)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_cuisines
    @cuisines = Cuisine.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @recipes = Recipe.all
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisines/edit.html.erb
<h1>Editar Cozinha</h1>

<%= flash[:error] %>

<%= form_for @cuisine do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit 'Enviar' %>

  <br> <%= link_to 'Voltar', root_path %> </br>
<% end %>

app/views/cuisines/new.html.erb
<% if flash[:error]%>
<%= flash[:error] %>
<% end %>
<ul>
  <% @cuisine.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<%= form_for @cuisine do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit 'Enviar' %>

  <br> <%= link_to 'Voltar', root_path %> </br>
<% end %>

app/views/cuisines/show.html.erb
<h1>Cozinha: <%= @cuisine.name %></h1>

<% if @cuisine.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de cozinha</p>
<% end %>


<% @cuisine.recipes.each do |recipe| %>
  <h1><%= link_to(recipe.title, recipe) %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
    <td><%= image_tag(recipe.image.url(:thumb)) %></td>
  </ul>
<% end %>

<%= link_to 'Editar', edit_cuisine_path if user_signed_in? and current_user.admin? %>
<br> <%= link_to 'Voltar', root_path %> </br>

app/views/home/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">CookBook</h1>
    <p><%= I18n.translate('site_description') %></p>
    <%= "Bem vindo: #{current_user.username}" if user_signed_in? %><br>
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <%= flash[:success] %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12 col-md-6">
    <h2>Últimas Receitas Cadastradas</h2>
    <% @recipes.each do |recipe| %>
      <%= render recipe %>
      <%= image_tag 'star.png' if recipe.highlight %>
    <% end %>
  </div>

  <div class="col-lg-12 col-md-6 favoritas">
      <h2>Receitas mais favoritadas dos usuários</h2>
      <% @favorite.each do |recipe|  %>
        <%= render recipe %>
        <%= image_tag 'star.png' if recipe.highlight %>
      <% end %>
    </div>

<div class="col-lg-12 col-md-6">
<% content_for :aside do %>
  <h1>Cozinhas</h1>
  <ul>
  <% @cuisines.each do |cuisine| %>
    <li><%= link_to cuisine.name, cuisine %></li>
  <% end %>
  </ul>
  </div>

<div class="col-lg-12 col-md-6">
  <h1>Tipo de Receitas</h1>
  <% @recipe_types.each do |recipe_type| %>
    <li><%= link_to recipe_type.name, recipe_type %></li>
  <% end %>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCookbook</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <main>

    <div>
      <%= form_tag("recipes/search", method: "get") do %>
      <%= label_tag(:search, "Buscar") %>
      <%= text_field_tag(:search) %>
      <%= submit_tag("Buscar") %>
      <% end %>
    </div>

    <div>
      <%= link_to 'Início', root_path %>
      <% if user_signed_in? and current_user.admin? %>
        <%= link_to 'Enviar uma receita', new_recipe_path %>
        <%= link_to 'Criar nova cozinha', new_cuisine_path %>
        <%= link_to 'Criar novo tipo de receita', new_recipe_type_path %>
        <%= link_to 'Atualizar Perfil', edit_user_registration_path %>
        <%= link_to 'Sair', destroy_user_session_path, method: "delete" %>
      <% elsif user_signed_in? %>
        <%= link_to 'Enviar uma receita', new_recipe_path %>
        <%= link_to 'Atualizar Perfil', edit_user_registration_path %>
        <%= link_to 'Sair', destroy_user_session_path, method: "delete" %>
      <% else %>
        <%= link_to 'Entrar', new_user_session_path %>
      <% end %>

    </div>

    <%= yield %>
  </main>
  <aside>
    <%= yield :aside %>
  </aside>
</body>
</html>

app/views/recipe_types/edit.html.erb
<h1>Editar Tipo de Receita</h1>

<%= flash[:error] %>

<%= form_for(@recipe_type) do |f| %>

<div>
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>

<%= f.submit 'Enviar' %>

<br> <%= link_to 'Voltar', root_path %> </br>
<% end %>

app/views/recipe_types/new.html.erb
<% if flash[:error]%>
<%= flash[:error] %>
<% end %>
<ul>
  <% @recipe_type.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

<%= form_for(@recipe_type) do |f| %>

<div>
	<%= f.label :name, 'Nome' %>
	<%= f.text_field :name %>
</div>

<%= f.submit 'Enviar' %>

<br> <%= link_to 'Voltar', root_path %> </br>
<% end %>

app/views/recipe_types/show.html.erb
<h1>Tipo de Receitas: <%= @recipe_type.name %></h1>

<% if @recipe_type.recipes.empty? %>
  <p>Nenhuma receita encontrada para este tipo de receitas</p>
<% end %>


<% @recipe_type.recipes.each do |recipe| %>
  <h1><%= link_to recipe.title, recipe %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
  </ul>
<% end %>

<%= link_to 'Editar', edit_recipe_type_path if user_signed_in? and current_user.admin? %>
<br> <%= link_to 'Voltar', root_path %> </br>

app/views/recipes/_recipe.html.erb
<h1><%= link_to(recipe.title, recipe) %></h1>
<ul>

  <li><%= recipe.recipe_type.name %></li>
  <li><%= recipe.cuisine.name %></li>
  <li><%= recipe.difficulty %></li>
  <li><%= recipe.cook_time %> minutos</li>
  <td><%= image_tag(recipe.image.url(:thumb)) %></td>
  
</ul>

app/views/recipes/edit.html.erb
<h1>Editar Receita</h1>

<%= flash[:error] %>

<%= form_for @recipe do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :recipe_type_id %>
  <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name %>
</div>
<div>
  <%= f.label :cuisine_id %>
  <%= f.collection_select :cuisine_id, @cuisines, :id, :name  %>
</div>
<div>
  <%= f.label :difficulty %>
  <%= f.text_field :difficulty %>
</div>
<div>
  <%= f.label :cook_time %>
  <%= f.text_field :cook_time %>
</div>
<div>
  <%= f.label :ingredients%>
  <%= f.text_area :ingredients %>
</div>
<div>
  <%= f.label :method %>
  <%= f.text_area :method %>
</div>
<div class="field">
  <%= f.label :image %><br/>
  <%= f.file_field :image %>
</div>
<div>
  <%= f.label :highlight %>
  <%= f.check_box :highlight %>
</div>
<%= f.submit 'Enviar' %>
<br> <%= link_to 'Voltar', root_path %> </br>
<% end %>

app/views/recipes/new.html.erb
<%= flash[:error] %>
<ul>
  <% @recipe.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>

<h1>Nova Receita</h1>
<%= form_for @recipe, url: recipes_path, html: { multipart: true } do |f| %>
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :recipe_type_id %>
  <%= f.collection_select :recipe_type_id, @recipe_types, :id, :name %>
</div>
<div>
  <%= f.label :cuisine_id %>
  <%= f.collection_select :cuisine_id, @cuisines, :id, :name  %>
</div>
<div>
  <%= f.label :difficulty %>
  <%= f.text_field :difficulty %>
</div>
<div>
  <%= f.label :cook_time %>
  <%= f.text_field :cook_time %>
</div>
<div>
  <%= f.label :ingredients%>
  <%= f.text_area :ingredients %>
</div>
<div>
  <%= f.label :method %>
  <%= f.text_area :method %>
</div>
<div class="field">
  <%= f.label :image %><br/>
  <%= f.file_field :image %>
</div>
<div>
  <%= f.label :highlight %>
  <%= f.check_box :highlight %>
</div>
<%= f.submit 'Enviar' %>
<br> <%= link_to 'Voltar', root_path %> </br>
<% end %>

app/views/recipes/search.html.erb
Resultados da busca por: <%= @search %>
<%= flash[:error] %>
<% @results.each do |recipe| %>
  <h1><%= link_to(recipe.title, recipe) %></h1>
  <ul>
    <li><%= recipe.recipe_type.name %></li>
    <li><%= recipe.cuisine.name %></li>
    <li><%= recipe.difficulty %></li>
    <li><%= recipe.cook_time %> minutos</li>
    <li><%= recipe.ingredients %></li>
    <li><%= recipe.method %></li>
  </ul>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
<%= 'Enviado por:' %>
<%= link_to "#{@recipe.user.username}", user_path %>
<%= flash[:success] %>
<h3>Detalhes</h3>
<p>
  Tipo: <%= @recipe.recipe_type.name %><br>
  Cozinha: <%= @recipe.cuisine.name %><br>
  Dificuldade: <%= @recipe.difficulty %><br>
  Tempo de preparo: <%= @recipe.cook_time %> minutos<br>
</p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>
<h3>Como Preparar</h3>
<p><%= @recipe.method %></p>

<h3>Imagem</h3>
<td><%= image_tag(@recipe.image.url(:medium)) %></td>

<hr>

<%= link_to 'Editar', edit_recipe_path if user_signed_in? and current_user.owner_recipe?(@recipe) %>
<%= link_to 'Remover', recipe_path, method: :delete if user_signed_in? and current_user.owner_recipe?(@recipe)%>
<% if user_signed_in? %>
  <% if current_user.favorite? @recipe %>
    <%=  link_to 'Desfavoritar', unfavorite_recipe_path(@recipe), method: :delete %>
  <% else %>
    <%= link_to 'Salvar como Favorita', favorite_recipe_path(@recipe), method: :post %>
  <% end %>
<% end %>
<%= link_to 'Voltar', root_path %>

app/views/users/show.html.erb
<div>
<br>
<h2>Informações do usuário </h2>
<table>
  <tr>
    <td>Nome:</td>
    <td><%= @user.username %></td>
  </tr>
  <tr>
    <td>Email:</td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td>Cidade:</td>
    <td><%= @user.city %></td>
  </tr>
  <tr>
    <td>Facebook:</td>
    <td><%= @user.facebook %></td>
  </tr>
  <tr>
    <td>Twitter:</td>
    <td><%= @user.twitter %></td>
  </tr>
</table>
</div>

<div class="row">
  <div class="col-lg-12 col-md-6">
    <h2>Receitas Cadastradas </h2>
      <% @recipes.each do |recipe|  %>
        <%= render recipe if recipe.user == @user %>
      <% end %>
  </div>